### ISSUE TITLE
Running nodejsscan changes files' contents

### ISSUE THREAD

**Issue by sergio-domingues** [ajinabraham/nodejsscan#109]
After running nodejsscan in my project directory it will end up with changes in some files (shown when performing git diff)

**Comment by awiddersheim** [comment]
I am seeing this as well. Doesn't really seem like the thing this tool should be doing.

**Comment by ajinabraham** [comment]
This is due to code beautify. I will see what can be done.

**Comment by ajinabraham** [comment]
Related: https://github.com/ajinabraham/NodeJsScan/issues/76

**Comment by ajinabraham** [comment]
Related: https://github.com/ajinabraham/nodejsscan/issues/76

**Comment by ajinabraham** [comment]
Take a look at our new CLI tool: https://github.com/ajinabraham/njsscan
Code Beautification is now removed in CLI
