### ISSUE TITLE
Not detecting SQL Injection

### ISSUE THREAD

**Issue by vysecurity** [ajinabraham/NodeJsScan#113]
Hey, it doesn't seem to be detecting SQL Injection even though there's a core rule for it?

I set a SQL statement and didn't escape, and it didn't pick it up.

**Comment by ajinabraham** [comment]
Do you have code sample that didn't get detected?

**Comment by vysecurity** [comment]
Let's say something like this, it doesn't detect:

```
connection.query(`
	INSERT INTO Tokens
	SET
token = ${input)},
	
`,
```

**Comment by JStyle21** [comment]
Hi,
I'm having the same issue, here is my code sample
`
function authenticate(req, res, next){
  const username = req.query.username,
        password = req.query.password
  let sqlRequest = new sql.Request(),
      sqlQuery = "select * from users where (username= '" + username + "' and password ='" + password + "')"
  sqlRequest.query(sqlQuery).then(function(recordset){
    if(recordset.length == 1){
      loggedIn = true
      //successful log in
    } else {
      authentication failed
    }
  })
  .catch(next)
}
`

**Comment by JStyle21** [comment]
I've tried a few test case none of them worked, i looked in the rules and it should have picked up the SELECT statement ...
Here are my test cases
https://www23.zippyshare.com/v/4uM0STJh/file.html

**Comment by ajinabraham** [comment]
Our current rules https://github.com/ajinabraham/NodeJsScan/blob/master/core/rules.xml#L124 may not detect that.

**Comment by JStyle21** [comment]
They don't...
How about if you change it to
`
(SELECT|INSERT|UPDATE|DELETE|CREATE|EXPLAIN)(.{0,40000})**|**(req\.|req\.query|req\.body|req\.param)
`
+ GMI flags

**Comment by ajinabraham** [comment]
The sample regex shared in stackoverflow or the comment above can throw too much false positives. It will get triggered for almost any SQL statement in code. Our current approach is to look for `request` parameters being concatenated with SQL statement in one line which is not the best, but a usable solution.
