### ISSUE TITLE
Helmet signature updates

### ISSUE THREAD

**Issue by eahousman** [ajinabraham/nodejsscan#116]
Helmet allows for running defaults using `app.use(helmet());`

This runs the default middleware:
```javascript
var DEFAULT_MIDDLEWARE = [
  'dnsPrefetchControl',
  'frameguard',
  'hidePoweredBy',
  'hsts',
  'ieNoOpen',
  'noSniff',
  'xssFilter'
]
```

Perhaps we should add `helmet\(\)` regex to those checks so that I don't need to enumerate those 7 helmet method calls to cover those checks:
```javascript
app.use(helmet.dnsPrefetchControl());
app.use(helmet.frameguard());
app.use(helmet.hidePoweredBy());
app.use(helmet.hsts());
app.use(helmet.ieNoOpen());
app.use(helmet.noSniff());
app.use(helmet.xssFilter());
```

Also, the CSP check does not include the Helmet method call `helmet.contentSecurityPolicy`.

Finally, for some reason my line `app.use(helmet.xssFilter());` is not clearing the missing header X-XSS-Protection:1 flag. Checking the regex directly says it should work, but in practice it isn't working... I will keep working on this, though.

**Comment by ajinabraham** [comment]
Thanks for the heads up. Will look into this soon.

**Comment by sfuerte** [comment]
if it's possible to detect such usage, it'll be even better:
```
app.use(helmet({
    // Content-Security-Policy
    "contentSecurityPolicy": {
       "directives": {
           "defaultSrc": ["'self'"],
           "scriptSrc": ["'self'", "'unsafe-inline'"]
      }
    },
    // X-DNS-Prefetch-Control
    "dnsPrefetchControl": { "allow": false },
    // Expect-CT
    "expectCt": {
        "enforce": true,
        "maxAge": 86400
    },
    // X-Frame-Options
    "frameguard": { "action": "deny" },
    "hidePoweredBy": {},
    // Strict-Transport-Security
    "hsts": {
        "includeSubDomains": true,
        "maxAge": 2592000
    },
    // X-Download-Options: noopen
    "ieNoOpen": {},
    // X-Content-Type-Options: nosniff
    "noSniff": {},
    // 'Cache-Control', 'Surrogate-Control', 'Pragma' and 'Expires' HTTP headers
    "nocache": {},
    "referrerPolicy": { "policy": "same-origin" },
    // X-XSS-Protection: '1; mode=block'
    "xssFilter": { "setOnOldIE": true }
}));
```

Here is a few more other examples, for `hpkp` specifically: https://github.com/venables/koa-helmet/blob/master/test/koa-helmet.spec.js

**Comment by ajinabraham** [comment]
Added.
Take a look at our new CLI tool: https://github.com/ajinabraham/njsscan
