### ISSUE TITLE
Regex isn't seeing my files

### ISSUE THREAD

**Issue by awiddersheim** [ajinabraham/NodeJsScan#120]
I have what I believe to be valid files but this regex is not considering them to be:

https://github.com/ajinabraham/NodeJsScan/blob/master/core/scanner.py#L19-L20

Anything we can do to just consider all `*.js` files as valid rather than subjecting them to this regex?

**Comment by ajinabraham** [comment]
The js file you have doesn't have a `require` or `export` in it?

**Comment by awiddersheim** [comment]
Yeah, these look like regular javascript files I guess. Not what you might consider nodejs specific.

**Comment by ajinabraham** [comment]
We use that regex to scan only server side node.js specific files as the rules are mostly applicable only to Node.js. 
Scanning client side js will generate unnecessary false positives.

**Comment by awiddersheim** [comment]
Thanks.
