### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by mhemrg** [ajinabraham/NodeJsScan#125]
Hey, well done :+1: 
Any plans to add i18n support? Or you may give some hints about the how-to.
That will be appreciated.

**Comment by ajinabraham** [comment]
@mhemrg What are expecting by i18n?
If it's just the timezone, the server always runs on user's timezone.

**Comment by mhemrg** [comment]
Thank you for your replay.
How about translating and localizing the rules?

**Comment by ajinabraham** [comment]
We won't be doing that, but open to PRs.
