### ISSUE TITLE
Feature Request - Upload Improvements

### ISSUE THREAD

**Issue by aress31** [ajinabraham/NodeJsScan#130]
Could you make it possible to upload multiple packages in a single go?

Let's say that I have 20 different packages to analyse, uploading them individually takes too long. Therefore, this feature would be useful for my use case and make life easier. :)

**Comment by ajinabraham** [comment]
Please Use CLI for this purpose.

**Comment by aress31** [comment]
Sure, where is the reference in the `Readme` or documentation stating that this could be achieved using the `CLI`?

It may be worth updating the `Readme` so people with a similar question can easily find the answer.

**Comment by ajinabraham** [comment]
Here is the CLI usage: https://github.com/ajinabraham/NodeJsScan#nodejsscan-cli
You will have to script it to scan multiple packages one after another.
