### ISSUE TITLE
issues with jsbeautify

### ISSUE THREAD

**Issue by devinrhode2** [ajinabraham/NodeJsScan#133]
So, our company uses gitlab ci pipelines, in the pipeline it runs gitlabs standard sast scan, among many other things.
One piece of our .gitlab-ci.yml files:
```
include:
  - https://gitlab.com/gitlab-org/gitlab-ee/blob/master/lib/gitlab/ci/templates/Security/SAST.gitlab-ci.yml
# https://docs.gitlab.com/ee/user/application_security/sast/
```

In gitlabs sast scan it uses NodeJsScan - this project. We are developing SPA's with create-react-app, NodeJsScan runs on our minified code. 

It generates confusing errors like this:
```
+----------------------------------------------------------------------------------------+
|            | NodeJsScan | build/static/js/1.bab07cdc.chunk.js:1                        |
|                                                                                        |
| Password Hardcoded                                                                     |
+----------------------------------------------------------------------------------------+
```

What it needs to do is use sourcemaps, and/or, format/beautify the minified javascript before running, so there is an actual line number. (webpack chunk files omit newlines entirely, everything is on one line). Another improvement would be to include a column number.

I've also had issue trying to use stage 3 ecmascript proposals like optional chaining causing syntax errors. This is yet another reason to upgrade the javascript formatting tool to babel. I am not sure how to use babel to create formatted/beautified output, but should not be hard.

**Comment by ajinabraham** [comment]
NodeJsScan beautifies the source files before performing a scan already.
https://github.com/ajinabraham/NodeJsScan/blob/master/core/scanner.py#L339

The gitlab version uses NodeJsScan rules, but it's a different tool written in Go and is totally out of our control. https://gitlab.com/gitlab-org/security-products/analyzers/nodejs-scan
