### ISSUE TITLE
Support for ECMAScript

### ISSUE THREAD

**Issue by mihir7293** [ajinabraham/nodejsscan#136]
.js files with ECMAScript may not contain require or modules.export
Due to below regex in Core/scanner.py file it is not considering file with contents of ECMAScript. Failure in below regex will skip file and will not scan code for rules.
```
NODE_RGX = re.compile(
    r"require\(('|\")(.+?)('|\")\)|module\.exports {0,5}= {0,5}") 
```

I guess regex should be updated and should have import,export also to support ECMAScript.

**Comment by ajinabraham** [comment]
Are these scripts intended to run at server side using Node.js or at client side via browsers?

**Comment by mihir7293** [comment]
ECMAScripts are just coding standards for javascript that is supported by Javascript Engine.  If used in Node.js it will run on server side.

Nodejs ECMA : https://nodejs.org/en/docs/es6/

Below link is for client side but similar code can be used on server side.
https://www.w3schools.com/js/js_es6.asp

**Comment by ajinabraham** [comment]
NodeJsScan by design will try to avoid scanning JavaScript files meant for client side to avoid false positives.
Let's just say you are using ECMAScript at server side. Can you `require()` them without `exports`?

**Comment by mihir7293** [comment]
I will check if we can differentiate by some means.

**Comment by skeggse** [comment]
My 2¢ is that users of NodeJsScan tend to know the anatomy of their project well, and are in a good position to configure something to explicitly delineate which files are Node files and which are browser-targeted. We have some files that are isomorphic and run in both contexts, which will likely make any heuristic-based approach inaccurate. I'd be happy to configure the tool either via a config file or a CLI flag.

**Comment by ajinabraham** [comment]
We don't distinguish between client side/server side javascript now.
Take a look at our new CLI tool: https://github.com/ajinabraham/njsscan
