### ISSUE TITLE
X-Powered-By false positive

### ISSUE THREAD

**Issue by sfuerte** [ajinabraham/NodeJsScan#140]
Getting the following false positives:
```
            {
                "description": "Remove the X-Powered-By header to prevent information gathering.",
                "tag": "web",
                "title": "Information Disclosure - X-Powered-By"
            }
```

An app uses Koa and doesn't show the subject header upon checking (see the attached image). Moreover, for testing, added to specifically remove it but to no avail, still getting the false positive:
```
> grep -r "X-Powered-By" my-lib/
my-lib//index.js:    ctx.remove("X-Powered-By");
```

![image](https://user-images.githubusercontent.com/16941995/69821760-c9c96200-11c1-11ea-8af7-bece8869686e.png)

**Comment by ajinabraham** [comment]
Fixed in latest master
