### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by arddluma** [ajinabraham/nodejsscan#145]
I used those commands: 
```
docker build -t nodejsscan .
docker run -it -p 9090:9090 nodejsscan
```
Zipped the .js file uploaded but no output, instead I got this error:
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>`

**Comment by ajinabraham** [comment]
Can you share the zip file that causes this issue?
