### ISSUE TITLE
Consider adding severity, rule id with the result

### ISSUE THREAD

**Issue by prabhu** [ajinabraham/nodejsscan#146]
Thanks for this excellent project. As mentioned [here](https://github.com/ajinabraham/NodeJsScan/issues/142#issuecomment-572564805) I am working on a SARIF convertor for this project.

To make the result more useful will you be able to add the following:

- severity for each finding
- rule id
- Optional a rule url with remediation tips etc. Eg: https://security.openstack.org/guidelines/dg_using-temporary-files-securely.html

Thanks in advance.

[Example sarif report](https://github.com/ajinabraham/NodeJsScan/files/4040621/nodejsscan-report.sarif.txt) . Remove .txt extn and use a suitable viewer.

**Comment by ajinabraham** [comment]
Take a look at our new CLI tool: https://github.com/ajinabraham/njsscan
