### ISSUE TITLE
Cannot import reports in defectdojo

### ISSUE THREAD

**Issue by karthik137** [ajinabraham/NodeJsScan#149]
Hi i  was trying to import results into defectdojo. But scan_type does not have option for NodeJsScan. Is it a bug in defectdojo or NodeJsScan is not supported anymore?.  But it is mentioned in the docs that NodeJsScan is supported.

**Comment by karthik137** [comment]
Attaching screenshot


![defectdojo](https://user-images.githubusercontent.com/19289544/73170857-73c35d00-4125-11ea-8d06-66255bfb33c3.png)

**Comment by ajinabraham** [comment]
You might want to check with DefectDojo project
