### ISSUE TITLE
SailsJS support

### ISSUE THREAD

**Issue by ebaynaud** [ajinabraham/nodejsscan#152]
Is it possible to add SailsJS support?

The issue with SailsJS is that we do not add express middleware with `app.use` as stated [here](https://sailsjs.com/documentation/concepts/middleware).

My config/http.js looks like this:
```js
const helmet = require('helmet')
module.exports.http = {
  ...
  middleware: {
    order: [
      ...
      'helmetProtection',
      ...
    ],
    helmetProtection: function helmetProtection(req, res, next) {
      return helmet({
        frameguard: {
          action: 'deny',
        },
        ...
      })(req, res, next)
    },
  },
```

Security headers are well set but NodeJsScan don't think so (because does not find `.use` if I understand well) and that makes my CI test fail...

**Comment by ajinabraham** [comment]
This is something we can add. I will consider this for the next release.

**Comment by ajinabraham** [comment]
Take a look at our new CLI tool: https://github.com/ajinabraham/njsscan
