### ISSUE TITLE
Issue using Docker Web UI

### ISSUE THREAD

**Issue by sbradford02** [ajinabraham/NodeJsScan#157]
I'm trying to test this out for the first time.  I'm getting the error below after uploading a small zipped js file.

Below is part of the stack trace.  Looks like it can't find the results table.

ERROR: relation "results" does not exist at character 661

STATEMENT: SELECT count(*) AS count_1

FROM (SELECT results.id AS results_id, results.scan_file AS results_scan_file, results.scan_hash AS results_scan_hash, results.locations AS results_locations, results.sha2_hashes AS results_sha2_hashes, results.hash_of_sha2 AS results_hash_of_sha2, results.sec_issues AS results_sec_issues, results.good_finding AS results_good_finding, results.missing_sec_header AS results_missing_sec_header, results.files AS results_files, results.total_count AS results_total_count, results.vuln_count AS results_vuln_count, results.resolved AS results_resolved, results.invalid AS results_invalid, results.timestamp AS results_timestamp

FROM results

WHERE results.scan_hash = '4a92755d5a8734d81327170efa8caec09d6f7fea6d189b9b4e93f6e41f0da749') AS anon_1

[2020-03-13 22:42:19 +0000] [34] [ERROR] Error handling request /upload/

**Comment by ajinabraham** [comment]
Not enough information.
Which docker?: Local build or from dockerhub
Docker logs
Problematic source code.
