### ISSUE TITLE
Pug rule for unescaped variable to be !{xyz} not #{xyz}

### ISSUE THREAD

**Issue by BanovMiroslav** [ajinabraham/NodeJsScan#158]
Pug rule is incorrectly considers #{variableName} to be unescaped.
Search for pug in https://github.com/ajinabraham/NodeJsScan/blob/master/core/rules.xml to see it.
Here's the actual pug docs that explain that # is for escaped variable and ! is for unescaped:
https://pugjs.org/language/interpolation.html

**Comment by kathyn-sm** [comment]
+1 is there a way to ignore this warning for now?

**Comment by ajinabraham** [comment]
This is fixed in latest master
