### ISSUE TITLE
Is there a way to ignore one line?

### ISSUE THREAD

**Issue by BanovMiroslav** [ajinabraham/NodeJsScan#159]
Is there a way to ignore a single line in a file?

For example with PHP_CodeSniffer you can make a comment such as this and it will cause the CoderSniffer to not check the next line:
// @codingStandardsIgnoreLine

I am not very familiar with this tool, so there may be some way that I don't know about?

**Comment by ajinabraham** [comment]
if you are using the Web UI, you can mark a finding as false positive or not applicable. The tool does not have a feature to ignore findings.
