### ISSUE TITLE
Does NodeJsScan support TypeScript?

### ISSUE THREAD

**Issue by yqxiaxia** [ajinabraham/NodeJsScan#161]
We have some projects that use TypeScript and need to use NodeJsScan.

As you know, before scan TypeScript, we should compile them to JavaScript firstly and this process would generate some intermediate files which would influence the scan result.

Do you guys have any idea about it?

**Comment by ajinabraham** [comment]
We do not support Typescript at this time. We are planning of rewriting NodeJsScan core soon. So we might support TypeScript in v3.
