### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by mjones11** [ajinabraham/NodeJsScan#164]
When attempting to execute the following docker command:

docker build -t nodejsscan .

I received the error: x509: certificate has expired or is not yet valid

Full trace:
C:\dev\NodeJsScan>docker build -t nodejsscan .
Sending build context to Docker daemon  6.173MB
Step 1/11 : FROM postgres:9.6.2-alpine
9.6.2-alpine: Pulling from library/postgres
cfc728c1c558: Pulling fs layer                                                                                                                                                                                     b749e72b24f9: Pulling fs layer                                                                                                                                                                                     0abdb8c9c36b: Pulling fs layer                                                                                                                                                                                     90ca3848ef7e: Waiting                                                                                                                                                                                              3ecf037a5034: Waiting                                                                                                                                                                                              9327e3c5554c: Waiting                                                                                                                                                                                              3133782bad17: Waiting                                                                                                                                                                                              143bac6c8910: Waiting                                                                                                                                                                                              d6da9f4bd18e: Waiting                                                                                                                                                                                              error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/bf/bf72189a3c51c803b0b0b146c0b4fad7811b3c53674755fc2a66f55ecfb8f4ac/data?verify=1586283298-15Z6G7T%2FVbg75rxrPgqdQRgocdE%3D: ****x509: certificate has expired or is not yet valid****

**Comment by ajinabraham** [comment]
This has nothing to do with NodeJsScan. It might happen that you are behind a proxy and cloudfare blocks you. This a network issue. Also consider updating docker
