### ISSUE TITLE
Support ignore files

### ISSUE THREAD

**Issue by skeggse** [ajinabraham/nodejsscan#167]
For some applications, it's not necessary to scan a subset of files in the tree. This can include the `.git` directory and a `node_modules` or `test` directory. It'd be nice if NodeJsScan could read a file similar to `.gitignore` (possibly a `.scanignore` or `.sastignore` file) to exclude some directories.

Alternatively, it'd be nice if the directory and file parameters were additive, so that you could run NodeJsScan on multiple directories and files in one go.

**Comment by ajinabraham** [comment]
Good Call! I am rewriting nodejsscan at this time. This will be tracked.

**Comment by ajinabraham** [comment]
Take a look at our new CLI tool: https://github.com/ajinabraham/njsscan

We have a `.njsscan` file for scan config

**Comment by prabhu** [comment]
Really glad this was added. I was doing numerous workarounds to make nodejsscan run properly with hanging on node_modules. Just started testing your njsscan app.
