### ISSUE TITLE
Add/Modify rules in rules.xml

### ISSUE THREAD

**Issue by L3m0nb4tt3ry** [ajinabraham/nodejsscan#168]
I tried modifying rules.xml by adding below rule(also added corresponding tag ) but it seems like the scanner is not picking up the updated rules? I have checked regex independently and its matching the pattern in source code.

```
<regex name="Custom - Information Exposure via error message">
<signature>(createErrorResponse\()(.{0,40000})(res\,|res\,)</signature>
<description>Error object is directly passed in create response, which may show stack strace to end users.</description>
<tag>InfoExposure</tag>
</regex>
```

I tried modifying the description section only but seems like that is also not reflecting. I think I am missing something here. Appreciate your help.

I am using NodeJSScan cli

**Comment by ajinabraham** [comment]
We are rewriting nodejsscan cli at the moment. I will consider this rule for development.

**Comment by ajinabraham** [comment]
Take a look at our new CLI tool: https://github.com/ajinabraham/njsscan

**Comment by ajinabraham** [comment]
if you share a sample code with `createErrorResponse(` I can add the rule.

**Comment by L3m0nb4tt3ry** [comment]
To avoid printing the sensitive information from response or error object in logs,
Code would look something like this
`function createBody(requestData, dummyalue){`\
` const body = {`\
`id: package.strings.username,`\
`password: package.strings.password,`\
`...`\
`}`\
`}`\
When object is created and used in logger it will print sensitive information
`const body = createBody(requestData, dummyvalue);`\
`const dummyoptions = createOptions(body);`\
`...`\
`logger.info(options);`\
Same scenario is for createErrorRespsone, If the req,res or error object contains sensitive information and it is passed in either createError or createErrorRespone it will print, the big problem with this approach is false positive since most of the objects will not have sensitive data, for this I was wondering how can we check this based on two conditions.
1. Whether the schema contains sensitive parameters . ( username/password in above case createBody function)
2. Whether CreateResponse or Logger prints the whole object.

In general to prevent verbose error message

**Comment by L3m0nb4tt3ry** [comment]
Checking new version, looks awesome, thanks for adding .njsscan config file.

**Comment by ajinabraham** [comment]
The `createBody()` or `createErrorResponse()` are not standard functions, but are user defined and hence we won't be able to support them. However you could add a rule to njsscan like https://semgrep.live/8Gqy under https://github.com/ajinabraham/njsscan/tree/master/njsscan/rules/semantic_grep
