### ISSUE TITLE
XSS False Negative 

### ISSUE THREAD

**Issue by security-monkey** [ajinabraham/nodejsscan#177]
A simple example like the following shows no findings.

```javascript
app.get('/', function (req, res) {
    var user = req.query.name;
    
    msg = "Hi " + user
    res.send('Response</br>' + msg);
});
```

**Comment by ajinabraham** [comment]
This would be detected if you initialize `msg`.
```
app.get('/', function (req, res) {
    var user = req.query.name;
    
    var msg = "Hi " + user
    res.send('Response</br>' + msg);
});
```

But I will tweak the rule to support uninitialized variables.

**Comment by security-monkey** [comment]
Yes but the xss works as written.

**Comment by security-monkey** [comment]
It misses even if msg is initialized but in an outer scope.... 

```javascript
var msg = '';
app.get('/3', function (req, res) {
    var user = req.query.name;
    
    msg = "Hi " + user
    res.send('Response</br>' + msg);
});
```

**Comment by ajinabraham** [comment]
I should be able to tweak the rules to support this. I need to check with semgrep folks before doing so.

**Comment by ajinabraham** [comment]
Should be covered by https://github.com/ajinabraham/njsscan/pull/11
