### ISSUE TITLE
False Negative - XSS

### ISSUE THREAD

**Issue by security-monkey** [ajinabraham/nodejsscan#178]
data flow into an object is not supported? 

``` javascript
app.get('/2', function (req, res) {
    var user = {user: req.query.name};
    res.send('Response</br>' + user.name);
});
```

**Comment by security-monkey** [comment]
same with arrays and other data types? 

```javascript
app.get('/1', function (req, res) {
    var user = req.query.name;
    var msg = [];
    msg.push(user);
    res.send('Response</br>' + msg[0]);
});
```

**Comment by ajinabraham** [comment]
The rules are based on semgrep patterns. Semgrep supports single file based data tainting.
https://github.com/ajinabraham/njsscan/blob/master/njsscan/rules/semantic_grep/xss_node.yaml

The initial version support string variables. Other datatypes needs to be added.

**Comment by security-monkey** [comment]
Ahh so just a grep and no data flow?

**Comment by ajinabraham** [comment]
semgrep does not support full blown taint analysis yet. It is more of a semantic aware grep. See https://github.com/returntocorp/semgrep#overview

**Comment by security-monkey** [comment]
ahh ok.. It looks like just a couple of string events and it gets thrown off. 

```javascript
app.get('/4', function (req, res) {
    var user = req.query.name;
    var header = "<html>";
    var msg = 'Hi ' + user;
    var footer = "</html>"; 
    var output = header + msg + footer;
    res.send( output);
});
```

**Comment by ajinabraham** [comment]
This is due to the limitation that tainting is not there yet.

**Comment by aryx** [comment]
We're working on it. 
Here is a very basic test file: https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/tests/TAINTING/tainting.py 
and the experimental yaml file to specify tainting: https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/data/basic_tainting.yml 
The idea is that you can use any kind of semgrep expression pattern to specify the source, sink, and sanitizer.

**Comment by ajinabraham** [comment]
Made some rule tweaks to support most of the examples here in https://github.com/ajinabraham/njsscan/pull/11
I can write a rule for this https://github.com/ajinabraham/nodejsscan/issues/178#issuecomment-644533780
but will wait till semgrep supports basic tainting. Closing this for now.

**Comment by security-monkey** [comment]
Ok.. i will create a new open issue around https://github.com/ajinabraham/nodejsscan/issues/178#issuecomment-644533780 then if you want to close this one.

**Comment by ajinabraham** [comment]
Sure, https://github.com/ajinabraham/njsscan/issues would be the right place.
