### ISSUE TITLE
Failure to parse modern JS

### ISSUE THREAD

**Issue by unusualbob** [ajinabraham/nodejsscan#179]
It seems whatever you're using for parsing javascript does not handle the current ecmascript standards.

Example failures:

```js
try {
 // something that throws
} catch ({ message }) {
  console.log(message);
}
```

```js
const [
 a = '1',
 b = '2',
] = existingVariable;
```
Both of these examples result in a parser failure.

**Comment by ajinabraham** [comment]
Opened a bug upstream with semgrep

**Comment by ajinabraham** [comment]
Fixed in latest version

**Comment by unusualbob** [comment]
Thanks for the fix :)
