### ISSUE TITLE
OperationalError: (psycopg2.OperationalError) FATAL:  role "root" does not exist`

### ISSUE THREAD

**Issue by kunal-relan** [ajinabraham/NodeJsScan#18]
Got this when uploading a zip file, OS macOS Sierra 10.12.1.

**Comment by ajinabraham** [comment]
Database connection issues.psycopg2.OperationalError) FATAL: role "root" does not exist`
Make sure you have proper access to PostgreSQL DB

**Comment by kunal-relan** [comment]
Ohhh thanks got it, I supplied my DB Username
