### ISSUE TITLE
SSI - setTimeout - Pattern is invalid

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [ajinabraham/nodejsscan#181]
# I couldn't find the CLI nor rules in the master branch of this application. Branch v3.7 still has core/rules.xml etc., so not sure where to contribute

The regular expression pattern for [`SSI - setTimeout`](https://github.com/ajinabraham/nodejsscan/blob/01528aaf9f7e511ef9b2c53b9fe3963ac1a1450e/core/rules.xml#L33) is invalid:
```py
import re
p = '(setTimeout\()(.{0,40000})(req\.|req\.query|req\.body|req\.param)'
s = 'req.socket.setTimeout(socketTimeout);if (req.query.foo) {'

# Will find a match
re.search(p,s)
```

So, I'm assuming the pattern should only match if there is req.* as an argument to `setTimeout`.

**Comment by ajinabraham** [comment]
We don't use regex anymore. The rules are available here: https://github.com/ajinabraham/njsscan/blob/master/njsscan/rules/semantic_grep/server_side_template_injection.yaml

**Comment by natlibfi-arlehiko** [comment]
Great! Thanks!
