### ISSUE TITLE
XSS - with the use of express-handlebars

### ISSUE THREAD

**Issue by melanierogan** [ajinabraham/nodejsscan#189]
Hello, wanted to say thank you for this really great tool and all the work you do. 

I wanted to flag that the scan picks up the use of `{{{body}}}` as being a XSS vulnerability, but this is a pattern that is recommended when you are making using of the [express-handlebars](https://github.com/ericf/express-handlebars#layouts) npm package. As far as I know, a XSS attack would not be possible in the way the body variable is rendered, so perhaps there is a way to flag this with nodejsscan where it detects the use of express-handlebars and `{{{body}}}`.

Totally happy to be corrected if I'm wrong and a XSS attack is possible in this case. Let me know.

Many thanks.

**Comment by ajinabraham** [comment]
Yes, this is a false positive. You can mark this as false positive within nodejsscan. For the next release, I will see if I can update the rule to not alert on `{{{body}}}`

**Comment by melanierogan** [comment]
Thanks so much for the quick reply 👍

**Comment by ajinabraham** [comment]
Addressed in latest master
