### ISSUE TITLE
Image not found opensecurity/nodejsscan:cli

### ISSUE THREAD

**Issue by dogmatic69** [ajinabraham/nodejsscan#191]
We have been using this in our CI and the image seems to no longer be available on docker hub as of a a few minutes. 

```
$ docker pull opensecurity/nodejsscan:cli
Error response from daemon: manifest for opensecurity/nodejsscan:cli not found: manifest unknown: manifest unknown
```

**Comment by ajinabraham** [comment]
@dogmatic69 nodejsscan:cli image is depricated. 
Please use https://github.com/ajinabraham/njsscan instead. You can find the image here https://hub.docker.com/r/opensecurity/njsscan
