### ISSUE TITLE
Web Interface: Wording

### ISSUE THREAD

**Issue by NF997** [ajinabraham/nodejsscan#192]
The web interface of the Docker container says "Upload".
However, the code to be analyzed doesn't really get uploaded anywhere (to an external server), right?

It might be good to rename this (maybe to "load"?) since it could potentially scare people off. E.g. when performing a code review of code another company owns I certainly don't want to "upload" it to external services...

**Comment by ajinabraham** [comment]
nodejsscan is an on premise solution. Code is not uploaded to cloud or external servers. Some of our users deploy it in internal network to be used by multiple users. Hence the terminology Upload is very relevant for us.
