### ISSUE TITLE
PWD fails 

### ISSUE THREAD

**Issue by mwithheld** [ajinabraham/nodejsscan#193]
`[node1] (local) root@192.168.0.18 ~
$ pip install njsscan
Collecting njsscan
  Downloading njsscan-0.1.2-py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 2.9 MB/s 
Requirement already satisfied: colorama>=0.4.3 in /usr/lib/python3.8/site-packages (from njsscan) (0.4.3)
Collecting libsast>=1.1.9
  Downloading libsast-1.2.0-py3-none-any.whl (39 kB)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3.8/site-packages (from libsast>=1.1.9->njsscan) (2.23.0)
Collecting semgrep==0.21.0; platform_system != "Windows"
  Downloading semgrep-0.21.0.tar.gz (63 kB)
     |████████████████████████████████| 63 kB 4.5 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2ek22yxt/semgrep/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2ek22yxt/semgrep/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2bde3p8n
         cwd: /tmp/pip-install-2ek22yxt/semgrep/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2ek22yxt/semgrep/setup.py", line 9, in <module>
        from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[node1] (local) root@192.168.0.18 ~
$ ./run.sh
bash: ./run.sh: No such file or directory
[node1] (local) root@192.168.0.18 ~
$ lll
bash: lll: command not found
[node1] (local) root@192.168.0.18 ~
$ ls
[node1] (local) root@192.168.0.18 ~
$ pip install njsscan
Collecting njsscan
  Using cached njsscan-0.1.2-py3-none-any.whl (94 kB)
Requirement already satisfied: colorama>=0.4.3 in /usr/lib/python3.8/site-packages (from njsscan) (0.4.3)
Collecting libsast>=1.1.9
  Using cached libsast-1.2.0-py3-none-any.whl (39 kB)
Requirement already satisfied: pyyaml>=5.3 in /usr/lib/python3.8/site-packages (from libsast>=1.1.9->njsscan) (5.3.1)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3.8/site-packages (from libsast>=1.1.9->njsscan) (2.23.0)
Collecting semgrep==0.21.0; platform_system != "Windows"
  Using cached semgrep-0.21.0.tar.gz (63 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_lmhl2_9/semgrep/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_lmhl2_9/semgrep/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vc29btkd
         cwd: /tmp/pip-install-_lmhl2_9/semgrep/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_lmhl2_9/semgrep/setup.py", line 9, in <module>
        from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by mwithheld** [comment]
I also tried a manual install, which failed
`[node1] (local) root@192.168.0.18 ~
$ git clone https://github.com/ajinabraham/nodejsscan.git
Cloning into 'nodejsscan'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 1954 (delta 9), reused 3 (delta 0), pack-reused 1929
Receiving objects: 100% (1954/1954), 5.32 MiB | 19.06 MiB/s, done.
Resolving deltas: 100% (699/699), done.
[node1] (local) root@192.168.0.18 ~
$ cd nodejsscan/
[node1] (local) root@192.168.0.18 ~/nodejsscan
$ python3 -m venv venv
[node1] (local) root@192.168.0.18 ~/nodejsscan
$ source venv/bin/activate
(venv) [node1] (local) root@192.168.0.18 ~/nodejsscan
$ pip install -r requirements.txt
Collecting njsscan==0.1.2 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/8e/e4/48544c5cc385264e5c06a21f999bdc486be592a81e2f6eb94563bc6709e0/njsscan-0.1.2-py3-none-any.whl
Collecting gunicorn==20.0.4 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
     |████████████████████████████████| 81kB 4.8MB/s 
Collecting flask==1.1.2 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl (94kB)
     |████████████████████████████████| 102kB 9.8MB/s 
Collecting jinja2==2.11.2 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl (125kB)
     |████████████████████████████████| 133kB 19.9MB/s 
Collecting psycopg2-binary==2.8.5 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/97/00/ed4c82364741031d745867f83820d4f373aa891098a5785841850491c9ba/psycopg2-binary-2.8.5.tar.gz (381kB)
     |████████████████████████████████| 389kB 39.0MB/s 
    ERROR: Command errored out with exit status 1:
     command: /root/nodejsscan/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4rgedhev/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4rgedhev/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-4rgedhev/psycopg2-binary/
    Complete output (23 lines):
    running egg_info
    creating pip-egg-info/psycopg2_binary.egg-info
    writing pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2_binary.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) [node1] (local) root@192.168.0.18 ~/nodejsscan`

**Comment by ajinabraham** [comment]
What are you trying to install nodejsscan or njsscan?
njsscan is the cli
nodejsscan is the vulnerability management system with a UI.

Error: pg_config executable not found.
is thrown because you may not have postgres installed in your system.

**Comment by mwithheld** [comment]
The manual install probably would have worked if I'd set up PostGres, yeah.
--

Starting from https://github.com/ajinabraham/nodejsscan
I hit the: "Try nodejsscan online: Try in PWD" link
which spun up the Docker machine to CLI.

I then imitated the demo under "Command Line Interface(CLI) and Python API"
pip install njsscan

**Comment by ajinabraham** [comment]
`pip install njsscan` should work on Linux or Mac except for alpine. Can you do a `pip install wheel` before installing `njsscan` if you still see issues, this might be due to semgrep. Please share your host os and version details for troubleshooting.

**Comment by mwithheld** [comment]
I'm just saying the "Try with PWD" link + the basic install lines does not
get you a working app.  Either the PWD link needs work or the install lines
could use a bit of fleshing out.

pip install wheel - this part worked
pip install njsscan - failed "ERROR: Failed building wheel for semgrep"

Not sure this works - here's the link:
https://labs.play-with-docker.com/p/bt8jsbaosm4g00edqjng#bt8jsbao_bt8jsbaosm4g00edqjo0

$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

**Comment by ajinabraham** [comment]
I think you got confused with PWD. PWD is a service to run docker containers online, you do not have to run any commands in the prompt there. It's already setup.

If you see a screen like this. Click on the port 9090 to access nodejsscan UI
![Screenshot 2020-09-03 at 3 48 19 PM](https://user-images.githubusercontent.com/4301109/92160433-008d7200-edfd-11ea-8d27-6c5fa50192fe.png)

**Comment by mwithheld** [comment]
I was trying for the CLI interface, so the first thing I did on entering the machine is
`[node1] (local) root@192.168.0.18 ~
$ njsscan
bash: njsscan: command not found
[node1] (local) root@192.168.0.18 ~
$ ls
[node1] (local) root@192.168.0.18 ~
`

I guess njsscan is not in the path.  So if I wanted to use the CLI, where would it be?

**Comment by ajinabraham** [comment]
If you want to use the CLI from PWD, you need to bash into the running container.
I would suggest you install it locally in your host via a
`pip install njsscan`
or use njsscan docker image 
https://github.com/ajinabraham/njsscan#docker

**Comment by mwithheld** [comment]
Not a bug.
