### ISSUE TITLE
How to use this tool on local code

### ISSUE THREAD

**Issue by buhshanpjoshi** [ajinabraham/NodeJsScan#2]
Hi Ajin,
It seems a very useful tool tfor the node.js project. I am currently working on the node js project and new to it.

can you please let me know exactly the steps how we can use it for the local code. In readme section its not specified.

It would be better and useful to have details steps to tool's execution.

Thanks and Regards,
Bhushan Joshi

**Comment by ajinabraham** [comment]
Instructions are available here http://opensecurity.in/nodejsscan/

**Comment by buhshanpjoshi** [comment]
Thanks Ajin for your quick response. I have generated my first report :)
