### ISSUE TITLE
[Feature Request] Allow to ignore lines

### ISSUE THREAD

**Issue by MartinThoma** [ajinabraham/nodejsscan#203]
I would like to include nodejsscan into a CI pipeline. When a potential issues is found, I want the pipeline to fail.

Sometimes, nodejsscan gives false-positives. Having an option to ignore those lines would be helpful.

## Suggestions

```javascript
// Flake8-style (Python)
const CHANGE_PASSWORD = 'a/password/route';  // noqa

// mypy-stile (Python)
const CHANGE_PASSWORD = 'a/password/route';  // nodejsscan: ignore

// Eslint-style (JavaScript)
const CHANGE_PASSWORD = 'a/password/route';  // nodejsscan-disable 

// other ideas
const CHANGE_PASSWORD = 'a/password/route';  // ignore
const CHANGE_PASSWORD = 'a/password/route';  // secure
const CHANGE_PASSWORD = 'a/password/route';  // reviewed
```

**Comment by ajinabraham** [comment]
nodejsscan uses njsscan underneath. So you can supress findings via https://github.com/ajinabraham/njsscan#suppress-findings

**Comment by MartinThoma** [comment]
Nice! So `//ignore: express_open_redirect` is the pattern :-)
