### ISSUE TITLE
[Feature Request] Allow configuration files

### ISSUE THREAD

**Issue by MartinThoma** [ajinabraham/nodejsscan#204]
It would be nice to be able to enable / disable rules for a project.

## Suggestion

If there is a `.nodejsscan.yaml` file in the scanned directory, parse it. It could look like this:

```
ignore:
  - node_tls_reject
  - node_timing_attack
warn:
  - node_password
```

This would mean that `node_tls_reject` and `node_timing_attack` are completely ignored. `node_password` is still be checked and potentially be shown as a warning, but not influence the exit code

**Comment by ajinabraham** [comment]
This is also already available.
see: https://github.com/ajinabraham/njsscan#configure-njsscan
