### ISSUE TITLE
Not detecting any errors 

### ISSUE THREAD

**Issue by Pol52** [ajinabraham/nodejsscan#205]
Hello, I have a web application I have made so that some of the OWASP top 10 vulnerabilities are in it. However when I scan it with nodejsscan I receive no errors whatsoevers and I was wondering why that's the case.
The vulnerabilities implemented are pretty simple and straightforward:
-SQL Injection
-Js/Html Injection
-XSS
-Unsafe cookies for session hijack

I believe I may be doing something wrong with the tool but I can't find what. For example, I have written this method:
```

User.create = function(username, email, password){  
    return new Promise((resolve, reject) => {
        var query = "INSERT INTO users" +
        " (username, email, password)" + 
        " VALUES ('" + username + "','" + email + "','" + password + "')";
        db.query(query , 
            (err, rows, fields) => {
                if(err){
                    reject(err);
                }else{
                    resolve(rows); 
                } 
            })
    })
}
```
to enable SQL Injection, but it's not detected.
I am using docker image and uploading the code both via github repo([https://github.com/Pol52/Vulnerabilities]) and via zip file. 
Can anyone point me in the right direction?
Thanks

**Comment by ajinabraham** [comment]
Hi @Pol52 

nodejsscan is based on semgrep rules. Take a look at the rules here: https://github.com/ajinabraham/njsscan/blob/master/njsscan/rules/semantic_grep/database/sql_injection.yaml

njsscan cannot do complex multi-file analysis. But will catch all the generic use cases when you have `req.foo` reaching an SQL injection sink. An example : https://github.com/ajinabraham/njsscan/blob/master/tests/assets/node_source/true_positives/sqli_node.js

We do this to reduce false positives. Unfortunately, we will miss some of the complex multi-file cases as semgrep does not support that.

**Comment by Pol52** [comment]
Thank you very much for replying to me @ajinabraham !
I do understand now, I will modify my code to comply.

I am closing the issue :)
