### ISSUE TITLE
File sizes to scan

### ISSUE THREAD

**Issue by vladimernan** [ajinabraham/NodeJsScan#22]
Is there any limit for files to be scanned. I tried .zip files over 100MB and seems like it's not working... scanner uploads them and sits there and does nothing for hours. Can you please advise?

**Comment by vladimernan** [comment]
To add details - I'm using docker to run the scanner

**Comment by ajinabraham** [comment]
Can you share any logs from the app?

**Comment by vladimernan** [comment]
I attempted 128MB size .zip file and it was like sitting on this whole eternity, then I just cancelled the job:
[INFO] Unzipping from Zip File

[INFO] Running Static Analyzer Running on - /root/.NodeJsScan/b20fbf07031ea0aed9c657798f6fec2136b2e9647f4628ffb68f57cfc4c75e6f/

**Comment by vladimernan** [comment]
I ran scan on 5MB file and it returned results:
[INFO] Unzipping from Zip File

[INFO] Running Static Analyzer Running on - /root/.NodeJsScan/052c19fc061df118d6861220d835fc5c1ae478da7ffca66f1c5fa669628a4b5e/

[INFO] Static Analysis Completed!
[INFO] Saving Scan Results!
172.17.0.1 - - [16/Jun/2017 21:31:11] "POST /upload/ HTTP/1.1" 200 -
172.17.0.1 - - [16/Jun/2017 21:31:12] "GET /result/052c19fc061df118d6861220d835fc5c1ae478da7ffca66f1c5fa669628a4b5e HTTP/1.1" 301 -
172.17.0.1 - - [16/Jun/2017 21:31:18] "GET /result/052c19fc061df118d6861220d835fc5c1ae478da7ffca66f1c5fa669628a4b5e/ HTTP/1.1" 200 -

**Comment by vladimernan** [comment]
I have increased memory, space and added CPUs on VM, as I suspected that there were no sufficient resources to run the scan. Not sure if that fixes issue in a long run. I suspect that after adding memory and power it may take a couple of hours to scan the file of that large size.

**Comment by vladimernan** [comment]
Or maybe I'm too impatient?

**Comment by ajinabraham** [comment]
The scan time is directly promotional to the file size and sometimes regex can cause it a bit exponential. Be patient :)

**Comment by vladimernan** [comment]
Thanks Ajin, but I have left it overnight - and seems it definitely has some issues with handling the large files. Mine is ~128MB. Finally it erred out with the message - server responded with 0 code. Does it ring any bells? Please help, if you can. As I said I am rinning Ubuntu workstation under Virtualbox and I am using the docker container to run the NodeJsScan tool...

**Comment by ajinabraham** [comment]
I cannot really help until i have access to the source code or problematic  file. I guess it's a regex DoS.
