### ISSUE TITLE
Python 3.7 is not available in the latest docker image

### ISSUE THREAD

**Issue by truff77** [ajinabraham/nodejsscan#284]
Hi,
latest docker image is failing when running the entrypoint.sh script because it calls:
/usr/bin/python3.7 manage.py recreate-db

python3.7 is not installed in the image, python3.9 is available. The fix should be pretty straightforward by just replacing python3.7 by python3 (which is a link to python3.9)

Cheers,
truff

**Comment by ajinabraham** [comment]
This is fixed. Thanks!
