### ISSUE TITLE
Test on file - not path - basis possible?

### ISSUE THREAD

**Issue by stefan-wiesner** [ajinabraham/NodeJsScan#3]
Hi. 

I like the test tool that much that I would like to implement it into a build process or pre-commit hook or so. For that it would be useful if I could set an array of files. Right now I can set -d /path/to/whatever. 

An -f [/path/to/file.js, /path/to/file2.js] would be perfect for those use-cases mentioned above. 

Any chance to extend nodeJsScan to accept on file-level?

Thanks in advance

Stefan

**Comment by ajinabraham** [comment]
Feature Added. Download the latest release: https://github.com/ajinabraham/NodeJsScan/releases/tag/v1.0

For usage Instructions, refer: https://github.com/ajinabraham/NodeJsScan/blob/master/README.md

**Comment by stefan-wiesner** [comment]
Wow that was fast.. Thanks alot!
