### ISSUE TITLE
Enable result post

### ISSUE THREAD

**Issue by cneumaier** [ajinabraham/NodeJsScan#59]
Hey @ajinabraham ,

is it possible to post a result.json generated by the cli.py command to the application and get the visualization from it. I love the cli option but i dont want to implement the html rendering of the output myself. 

Thanks

**Comment by ajinabraham** [comment]
I am not understanding your question. You have access to the JSON generated by the CLI here

https://github.com/ajinabraham/NodeJsScan/blob/master/cli.py

and you can add your custom logic there to suite your requirements.

**Comment by cneumaier** [comment]
I want to use the integrated visualization of the application. 

Imagine the following process: 
- creating Json-file via CI (works perfect)
- post to the application running in docker to show results in browser 

I want to use your already implemented result.html to render the results. 
I hope this clarifies the use case better

**Comment by ajinabraham** [comment]
Script your on code to read the json file and post or modify the cli to read the json output and post directly from there
