### ISSUE TITLE
When I upload JS files tells me that JS files are not an allowed type

### ISSUE THREAD

**Issue by dgonzalez** [ajinabraham/NodeJsScan#6]
Any idea on why?

**Comment by ajinabraham** [comment]
Please zip them and upload.

Regards,

*Ajin Abraham  *
Security Researcher
<https://twitter.com/ajinabraham>    <http://in.linkedin.com/in/ajinabraham>
  <https://github.com/ajinabraham>
m +91-9633325997 a Bangalore,India
s opensecurity.in s opsecx.com

**Comment by dgonzalez** [comment]
Works! I think a note in the error would be very helpful.

**Comment by ajinabraham** [comment]
Updated Index.html
