### ISSUE TITLE
XSS In NodeJsScan UI from File / Folder Names. 

### ISSUE THREAD

**Issue by matt-** [ajinabraham/NodeJsScan#7]
Hey man. Great project. Thank you for your work on this. 

I was testing this out and bumped in to an XSS. 

1. Create a zip file with a file named: ');alert(document.domain);('.txt
2. Upload the zip. 
3. Under "All Files" link under location for the file. 
4. You should see a popup with the xss. 

<img width="1138" alt="screenshot 2017-02-15 23 45 35" src="https://cloud.githubusercontent.com/assets/453602/23012013/f04cd8c6-f3d8-11e6-91f3-ff7bf3063c07.png">

This gets converted into the following HTML: 
```html
<a href="javascript:view('e9ce45f4ef683fb3130c00e93a96fd92c63010b0597249012d47c4f80863663d/tester/&#39;);alert(document.domain);(&#39;.txt','0','tester&#39;);alert(document.domain);(&#39;.txt','e9ce45f4ef683fb3130c00e93a96fd92c63010b0597249012d47c4f80863663d');">
```

The single quote is being html encoded instead of properly escaped for javascript.

**Comment by ajinabraham** [comment]
Nice Catch. Should be fixed with: https://github.com/ajinabraham/NodeJsScan/commit/df968474956d1deb7eca7949eee14a57154dab01#diff-3f41e546893dc64b71aaacad12cad815

A perfect example of why html escaping provided by the framework is not sufficient against all xss contexts.
