### ISSUE TITLE
Corrupts Handlebars templates with `json` in the file name

### ISSUE THREAD

**Issue by keithws** [ajinabraham/nodejsscan#76]
Very promising static code analyzer for node.js. However, I was very surprised to find that it modified some of my files and corrupted them no less. The issue seems to be related to files with names like `index.json.hbs` this is a Handlebars template that outputs JSON.

After running `nodejsscan`, these files where modified and it appears that it attempted to format the Handlebars as JSON, so the double curly braces get line breaks and indented.

Please fix. I'd like to add this to our build step, but it cannot modify files.

**Comment by ajinabraham** [comment]
Hi @keithws NodeJsScan beautifies the code before static analysis. This is not a problem if you are using Static Analysis via GUI as a copy of the code is made, but can be problematic when you are running CLI. I will see what I can do.

**Comment by keithws** [comment]
I think you can remove/comment out line 182 in core/scanner.py. Seems unnecessary since you are returning the beautified data.

**Comment by prabhu** [comment]
https://github.com/ajinabraham/NodeJsScan/blob/master/core/scanner.py#L345 - Do you need any PR for this one? In general, scanners can only read contents and write reports to a separate directory. Anything else will not be accepted by developers and organizations alike.

**Comment by keithws** [comment]
Agreed. I was not expecting it to modify any of my files. It should be a read-only operation.

**Comment by ajinabraham** [comment]
I am currently rewriting nodejsscan. I will add a flag to prevent beautify for cli

**Comment by ajinabraham** [comment]
Closing in favour of #109
