### ISSUE TITLE
DESC: 'ascii' codec can't encode characters in position 29-39: ordinal not in range(128)

### ISSUE THREAD

**Issue by slazht** [ajinabraham/NodeJsScan#9]
I got this error 

[2017-03-06 12:07:18]
Error Performing Code Analysis
FILE: /home/samdon/NodeJsScan/core/scanner.py
LINE: 232 - str(finding["lines"]))
DESC: 'ascii' codec can't encode characters in position 29-39: ordinal not in range(128)

how to fix it ?

**Comment by ajinabraham** [comment]
can you share the file or zipped package that caused this issue. It should be an unicode bug.

**Comment by slazht** [comment]
this is the zip file 
https://expirebox.com/download/59a9ce0fa798eb77c85c479d16d30571.html

**Comment by ajinabraham** [comment]
This should be fixed in latest master, try again
