### ISSUE TITLE
Rule for Security Header Check for "X-Content-Type-Options" and "X-Download-Options" is wrongly set

### ISSUE THREAD

**Issue by parthkdas** [ajinabraham/NodeJsScan#98]
Rule for Security Header Check for "X-Content-Type-Options" is wrongly set.

It is failing 
` res.setHeader('X-Content-Type-Options', 'nosniff'); `
`res.setHeader('X-Download-Options','noopen');`

But passess
`res.setHeader('X-Content-Type-Options', '""nosniff');`
`res.setHeader('X-Download-Options','""noopen');`

The bug is due wrong value in rules.xml 

**`<signature>helmet.noSniff|require\(('|")dont-sniff-mimetype('|")\)|nosniff\(\)|X-Content-Type-Options('|")*(\s)*(:|,)(\s)*('\"")*nosniff</signature>`**

**`<signature>require\(('|")ienoopen('|")\)|ienoopen\(|helmet.ienoopen\(|X-Download-Options('|")*(\s)*(:|,)(\s)*('\"")*noopen</signature>`**

The correct value should be 

**`<signature>helmet.noSniff|require\(('|")dont-sniff-mimetype('|")\)|nosniff\(\)|X-Content-Type-Options('|")*(\s)*(:|,)(\s)*('|")*nosniff</signature>`**

**`<signature>require\(('|")ienoopen('|")\)|ienoopen\(|helmet.ienoopen\(|X-Download-Options('|")*(\s)*(:|,)(\s)*('|")*noopen</signature>`**

**Comment by ajinabraham** [comment]
Thanks for the report. Fixed in master
https://github.com/ajinabraham/NodeJsScan/commit/2c17d64e5661f6e4ee2b1454f18f902557bab16c
